### ISSUE TITLE
 Make code forwards-compatible with Python 3.9

### ISSUE THREAD

**Issue by driesmp** [matthewdeanmartin/colorclass#1]
https://github.com/Robpol86/colorclass/pull/27

Please include this if the other github is dead (Robpol86).

Which code repo is shipped with the PyPi package, is that yours @matthewdeanmartin ?

**Comment by driesmp** [comment]
Oh its already included. Sorry about that.

**Comment by matthewdeanmartin** [comment]
Since my main goal was to get a wheel published, I only verified (almost) all tests ran w/code as is & did a 2 line fix for the 3.10 namespace change. I'm happy to see folk still care about this library!
