### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by ThiefMaster** [matthewdeanmartin/colorclass#3]
Not much to say except that nobody should be using Python 2 nowadays, and those who do can use the current version of this library.

PS: Thanks for reviving this; like this I can remove the vendored version and still support Python 3.10!

**Comment by matthewdeanmartin** [comment]
I have been removed as a collaborator by Robpol86 (not sure why). Since he owns the pypi name, you'll have to take up any requests with him.
